### ISSUE TITLE
255 code

### ISSUE THREAD

**Issue by Yohaden** [ben-z/Silent-Sync#9]
Hi, I'm trying your package to work my code on my computer and test it on my raspberry pi.
I usually commit the changes in github then pull them in the raspberry but it's too many manipulations for sometime really few changes.
I'm testing my raspberry pi on a console thru ssh so I now for sure that the ssh is working between my two computers but i still have the error 255.
here is the silent-sync.json
{
  "enabled": true,
  "host": "192.168.1.39", // local ip of my pi
  "port": 22,
  "username": "pi", // username of my pi
  "remoteDir": "/home/pi/Blacksad", // i never know if it's /home/pi/folder or /home/folder but i tried both)
  "exclude": [
    "/_img" // one folder i don't want
  ],
  "include": [
    "/Fritzing" 
  ],
  "deleteRemoteFiles":true,
  "rsyncFlags": "avz"
}

on the mac when i do
ssh pi@192.168.1.39 it's working just fine

any idea ?

**Comment by ben-z** [comment]
Hello @Yohaden looks like it's that dreaded permission issue again. Take a look [here](https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys--2) and see if there's anything missing from the systems (`~/.ssh/id_rsa.pub` on the mac and the corresponding content in `~/.ssh/authorized_keys` on the pi). It may be completely irrelevant since the `ssh` command is working.

Also can you please post the log from the developer console? (<kbd>command</kbd> + <kbd>option</kbd> + <kbd>i</kbd>)

**Comment by Yohaden** [comment]
Ok my bad, I did the other way (i had authorized_keys on the mac and the is_rsa.pub on the pi. 
Now it’s working fine. Sorry for the newbie question, and since I’m french i have misunderstood the tutorial.

I’m really happy with atom.io … i just saw that they will release a 1.0 version in june, i hope it will still be a freeware.

Thank you very much for the quick answer
Best,

Youenn

**Comment by ben-z** [comment]
Glad to know that it's working! If there are any more questions or concerns feel free to open a new issue or contact me directly through [Twitter](https://twitter.com/ben785314280). Thanks for using Silent Sync!
